### ISSUE TITLE
design UI for wavelength range limiting

### ISSUE THREAD

**Issue by RelevantPlay** [publiclab/spectral-workbench#1]
The current version of Spectralworkbench is hard-coded to display reflectance spectra between 250 and 800nm. Since the webcam is sensitive past 800nm, could you add functionality in the UI to extend this display to spectra beyond 800nm (say 850nm or so)? 

Thanks! -david mccloskey

**Comment by jywarren** [comment]
yes! We'll be adding this soonish; probably using tags, with a UI as well. Thanks!

**Comment by jrslagle** [comment]
Jeff, were you thinking of adding this feature as a clickable axis or under More Tools, or both?

**Comment by jywarren** [comment]
I'm currently working on a d3-based graphing system, the scope of which is
quite large: https://github.com/publiclab/spectral-workbench/pull/139

This will definitely include zooming. David - how urgent is your request? I
could prioritize getting a basic version of the d3 graphing into
set/spectra page display, but I was thinking of doing some under-the-hood
database optimization work first.

**Comment by jrslagle** [comment]
Sounds good, I'll leave this one alone.

**Comment by jywarren** [comment]
Completed and deployed as part of #139!

**Comment by jywarren** [comment]
Actually we could/should create a UI around this. So... reopening. :-)

**Comment by jywarren** [comment]
This is complete in the latest d3-graphing branch, and will be merged soon. Thanks!!!
