### ISSUE TITLE
spectra appear in wrong place when comparing

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/spectral-workbench#10]
In doing a comparison, the 20W-50 spectra is offset by 100nm.
![screen shot 2014-09-18 at 1 21 08 pm](https://cloud.githubusercontent.com/assets/1203280/4326638/7f9660f2-3f71-11e4-88c7-0861a386a3a9.png)

![screen shot 2014-09-18 at 1 21 29 pm](https://cloud.githubusercontent.com/assets/1203280/4326642/8bb3dffe-3f71-11e4-93a7-a455da0f0dca.png)

Upon saving the set it appears in the right place.
![screen shot 2014-09-18 at 1 23 48 pm](https://cloud.githubusercontent.com/assets/1203280/4326672/c3a5edb2-3f71-11e4-880e-9f26684f4d3c.png)

**Comment by jywarren** [comment]
I believe we investigated this further Mathew, and found that it only happened with a newly created spectrum, I think? What were the conditions in which it happened? Vpowerrc, can you try with a newly created spectrum via the /upload interface?

**Comment by jywarren** [comment]
Should be resolved in v2 graphing library once new comparisons feature rolls out
