### ISSUE TITLE
Toggle RGB

### ISSUE THREAD

**Issue by Stoft1** [publiclab/spectral-workbench#109]
Just a small bit -- the initial 'combined' spectral plot is 'white' to differentiate from the RGB plot colors .... but when toggled back, that same plot is 'red' which is likely confusing for most and a bit deceiving (unless you happen to remember the shape of the original combined data. Probably a 5-min fix.

**Comment by jywarren** [comment]
This should no longer be an issue in the v2.0 revisions; see for example http://publiclab.org/notes/warren/08-06-2015/wavelength-range-limiting-in-spectral-workbench
