### ISSUE TITLE
A fix for the CFL calibration

### ISSUE THREAD

**Issue by Stoft1** [publiclab/spectral-workbench#112]
I discovered why there's been some residual peak misalignment with listed wavelengths after a SWB CFL calibration; which some have attempted to fix using complex polynomial curve-fit algorithms. The present calibration is based only on a linear 2-point approximation. However, it would be better to use a calculation for dispersion based on the diffraction angle light being intercepted by a flat image plane. See research note: http://publiclab.org/notes/stoft/03-02-2015/cfl-cal-error-explained for more discussion on the topic.

**Comment by jywarren** [comment]
Merging into #55
