### ISSUE TITLE
Log in issue with smartphone

### ISSUE THREAD

**Issue by Slivias** [publiclab/spectral-workbench#113]
Hello. I have a serious problem with login. If i use pc everithing is ok using smartphone instead, i can log in publiclab.org but when switch to spectralworkbench i'm no more logged. If i try to login directly from spectralworkbench the site neither log in me nor give an error message. I tried chrome, firefox and opera.

**Comment by jywarren** [comment]
Hi, I'm sorry you're having trouble -- what do you see instead of being
logged in? What is your username?

**Comment by mikaelnelson** [comment]
This is happening to me on my desktop as well. On IE and Chrome.

**Comment by Slivias** [comment]
Hi!
my username is sharky.
I try to explain each passage because can't do screenshot in this moment.
From spectralworkbench.org  pressing login is opened a pop-up window which request my users, i insert it and then press login button. This redirect me in the page where the site asking if I trust this site with my identity and  pressing Yes I am redirecting to spectralworkbench.org without to be logged in.

After ten times the log in was successful.

**Comment by jywarren** [comment]
Did you see that I believe this was fixed last week? Can you try again and
confirm if it's still not working? Thanks!

**Comment by Slivias** [comment]
Oh sorry!! I check right now with different browser and send the results!
sorry again for my distraction and thanks for your incredible work.

2015-03-23 15:32 GMT+01:00 Jeffrey Warren <notifications@github.com>:

> Did you see that I believe this was fixed last week? Can you try again and
> confirm if it's still not working? Thanks!
>

**Comment by jywarren** [comment]
Thank you for your help!!!

**Comment by Slivias** [comment]
Good news. Now works properly with Opera and Firefox (I am testing with
Android 4.4) but not with Chrome with after the request of login resend me
at the homepage of publiclab.
I don't know if it is a useful information.



2015-03-23 15:40 GMT+01:00 Jeffrey Warren <notifications@github.com>:

> Thank you for your help!!!
>

**Comment by jywarren** [comment]
Thanks, chrome desktop? What version, os? Thanks!

**Comment by Slivias** [comment]
Chrome 41.0.2272.94 on Android 4.4.2


2015-03-23 15:45 GMT+01:00 Jeffrey Warren <notifications@github.com>:

> Thanks, chrome desktop? What version, os? Thanks!
>

**Comment by jywarren** [comment]
I wasn't able to reproduce on Chrome 41.0.2272.96 (i.e. it works for me); are you logged in to PublicLab.org on Chrome when you try it?

**Comment by Slivias** [comment]
Good morning Jeffrey,
i go directly on spectralworkbench.org, the site require the username and
redirect me on publiclab.org/login, inserted again user and psw is open
publiclab.org without login.
But I think is a mobile problem because I have tried with another mobile, a
samsung galaxy trend lite with chrome 30.0.1599.82 ant it works.

I continue to try uploading my mobile and keep you update.

2015-03-23 21:50 GMT+01:00 Jeffrey Warren <notifications@github.com>:

**Comment by jywarren** [comment]
Hmm, OK - perhaps you could try in an Incognito tab on the original phone?

**Comment by Slivias** [comment]
nothing,,,not even in incognito mode...at this point i wait the next
release of chrome and will try again.


2015-03-24 22:39 GMT+01:00 Jeffrey Warren <notifications@github.com>:

> Hmm, OK - perhaps you could try in an Incognito tab on the original phone?
>
>

**Comment by jywarren** [comment]
That is so strange that it's just the one device. If you do have a chance
to test it on another phone with the same *version* of Chrome, that might
be helpful. My version was not identical, just very close.
