### ISSUE TITLE
"Compare to live" feature is broken

### ISSUE THREAD

**Issue by wecapa** [publiclab/spectral-workbench#115]
I've been experimenting with my Desktop Spectrometer and was trying to recreate the "compare to live" feature discussed in one of the tutorial videos.  When I select "compare" while viewing a live spectra, I get a list of previously acquired spectra, but upon selecting one, the window returns to the live spectra, but the comparison spectra isn't there.  

This issue has been confirmed by another user.

**Comment by jywarren** [comment]
I'm sorry to say I think we're going to deprecate this feature in favor of the much more robust non-live comparison system in 2.0. The tutorials will be updated to match.

If you feel strongly about this, please re-open and we can consider it for 2.1. Thank you!
