### ISSUE TITLE
/capture doesn't sample from the middle by default

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/spectral-workbench#12]
at startup in the settings menu, if no cross-section is selected and I just click "Begin Capturing" I do not see the middle cross section when I start capturing.
![screen shot 2014-09-21 at 4 50 47 pm](https://cloud.githubusercontent.com/assets/1203280/4350455/7fc3c29c-41ea-11e4-942a-f74ff8d3966d.png)
![screen shot 2014-09-21 at 4 48 25 pm](https://cloud.githubusercontent.com/assets/1203280/4350457/9e3a998a-41ea-11e4-84d0-edc92e2f86b5.png)
There should be a default cross section-- and I  remember there being one before... seems like a new problem.

**Comment by jywarren** [comment]
I believe this is resolved in the latest code, to deploy early next week.
