### ISSUE TITLE
safari live capture doesn't work, needs warning about browsers

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/spectral-workbench#123]
clicking on live capture on Safari isn't working and goes to the upload screen.  can we add a warning that safari doesn't work for live capture when this happens?

![screen shot 2015-05-13 at 12 04 48 pm](https://cloud.githubusercontent.com/assets/1203280/7618649/605c99ca-f968-11e4-918d-ad15b03ad12f.png)

**Comment by jywarren** [comment]
Oh, actually since safari doesn't support webcam access, that's supposed to
be a feature, but you're right, we should flash a warning.
