### ISSUE TITLE
calibration not finishing in Firefox on mac os

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/spectral-workbench#124]
I'm filing this bug for bluemountainsurfer -- so I don't have the full story.  From his description, he's beginning a calibration, but after clicking the blue line never gets a pop-up prompt about the green line. Here's his screenshot:
![screen shot 2015-05-13 at 3 00 00 pm](https://cloud.githubusercontent.com/assets/1203280/7619961/2fc43922-f971-11e4-9091-956445b02ae5.png)

**Comment by jywarren** [comment]
We're currently rewriting the entire calibration system in #167, so closing. Thanks!
