### ISSUE TITLE
calibration issue

### ISSUE THREAD

**Issue by Slivias** [publiclab/spectral-workbench#125]
Hello,
in spectralworkbench my user is sharky.
I have got a little issue. Analyzing some LED and using my calibration i have the right wavelength for the blue led (around 450nm) and wrong value for yellow and red. Then I have copied the calibration of user scottax2 obtaining good value for leds red and yellow, but wrong for blue one (shifted the wavelength around 600nm).
Also I don't understand why the spectrometer software works only if I use my mobile tited, in straight way doesn't acquire spectra 
in this way works: 
![screenshot_2015-06-04-13-25-44](https://cloud.githubusercontent.com/assets/11555651/7983556/dc32cd52-0ac1-11e5-9ca4-f14fd22dbc76.png)

in this one no: 
![screenshot_2015-06-04-13-23-46](https://cloud.githubusercontent.com/assets/11555651/7983561/e78131e4-0ac1-11e5-847c-e2a52e286228.png)

Help!

thank u very much

Silvia

**Comment by jywarren** [comment]
Unfortunately we can't lock the camera tilt sensor; it's too bad! 

As to your spectra, can you share a link to one? For calibration, you need to calibrate your own device; somebody else's data won't be aligned the same way. 

Sorry you're having trouble!

**Comment by jywarren** [comment]
Closing as no response was found; please re-open if you see this and still have an issue! Thanks.
