### ISSUE TITLE
prompt to reload if new calibration becomes available (changed)

### ISSUE THREAD

**Issue by jywarren** [publiclab/spectral-workbench#14]
this involves making the differences between logged-in and non-logged-in interfaces solely javascript-based; no erb template conditionals. And a `$W.analyze.toggleLoggedIn()` call to switch them over. Maybe `.logged-in` and `.logged-out` classes?

**Comment by Sreyanth** [comment]
This would be nice. I think we should include all our offline version in the `.logged-out` class as well. Whenever the device is connected to internet, we could login and switch to `.logged-in` class.
