### ISSUE TITLE
Spectral workbench spectrum CSV file data error

### ISSUE THREAD

**Issue by anks123** [publiclab/spectral-workbench#140]
Hey 

So I tried downloading the CSV file today for a spectrum and once the file is downloaded and loaded onto a spreadsheet, the wavelengths show up to be 0 for everything.
anything that can be done ?

**Comment by jywarren** [comment]
You're right - will try to work on that today. Sorry for the bug! Are you
interested in contributing code, at all? Thanks!

**Comment by jywarren** [comment]
Fixed! Thanks again.

**Comment by anks123** [comment]
Thanks! well I'm not an expert coder, I'd try though

**Comment by jywarren** [comment]
Hey, every thing helps. The first step is getting Spectral Workbench
installed; have you tried that?

**Comment by anks123** [comment]
No havent tried that yet .. where can I install it from ?

**Comment by jywarren** [comment]
There are instructions at https://github.com/publiclab/spectral-workbench
-- and please reach out on the developers list (
http://publiclab.org/wiki/developers) if you need some help getting it
started! Thanks.
