### ISSUE TITLE
Errorpage when saving spectrum with existing calibration

### ISSUE THREAD

**Issue by YogiBGitHub** [publiclab/spectral-workbench#146]
The "We're sorry, but something went wrong" page appears when trying to calibrate a spectrum with an existing calibration. But when going back to the actual spectrum, it seems to have been calibrated any way. Also, a new calibration does not appear in the list when choosing to use an existing calibration. I have also noticed that when smoothing a spectrum ten lines below, the spectrum is not saved. So - I guess there is an issue with the filesystem... or something like that.
Bjorn

**Comment by jywarren** [comment]
Thanks a lot - I have a fix for this which I hope to post shortly.

**Comment by jywarren** [comment]
Hi, I pushed the new changes - can you check that this works now?

**Comment by YogiBGitHub** [comment]
Thanks a lot. Now it works very well again.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 11. august 2015 21:50
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub
Emne: Re: [spectral-workbench] Errorpage when saving spectrum with existing calibration (#146)

 

Hi, I pushed the new changes - can you check that this works now?
