### ISSUE TITLE
graceful embed fallback using javascript plus a `blockquote` default

### ISSUE THREAD

**Issue by jywarren** [publiclab/spectral-workbench#156]
This isn't that important.

**Comment by btbonval** [comment]
I am going through 50+ issues in my inbox between PL and my work. The content of this one is by far my favorite for the evening.

**Comment by jywarren** [comment]
:-)

**Comment by jywarren** [comment]
Currently looks like this when JS doesn't load:

![screenshot 2015-09-18 at 12 23 59 pm](https://cloud.githubusercontent.com/assets/24359/9964780/35f82990-5e00-11e5-9c35-757c4c0147cf.png)
