### ISSUE TITLE
mobile selection of cross section does not show data in live graph during capture

### ISSUE THREAD

**Issue by bearacuda** [publiclab/spectral-workbench#21]
![screenshots_2015-01-06-15-55-50](https://cloud.githubusercontent.com/assets/10427894/5638681/76588fc0-95bf-11e4-9ce5-b0705aacbf26.png)
![screenshots_2015-01-06-15-54-58](https://cloud.githubusercontent.com/assets/10427894/5638682/78ade40a-95bf-11e4-8400-648f15534e9b.png)
I have attached two screenshots from my Galaxy Note 3 smartphone.  I am using the smartphone DIY instructions and the back facing camera.  I found first that the online spectralworkbench utility does not work with both Chrome (back facing camera only displays 'black' with nothing covering camera!) and Opera.  I can only use it properly with current Firefox.  The screenshots come from the DIY spec/smartphone pointed at a perfectly white display on a 12" tablet.  Why when I perform the capture does NOTHING SHOW UP!  I have also tried to point it at a compact fluorescent, but same thing happens.  What am I doing wrong?
Thank you,
Jason

**Comment by jywarren** [comment]
Hi, Jason - this is a bit mysterious; have you tried using your finger to manually select a different yellow cross section? Perhaps the yellow line is not actually positioned there, but doing it again manually would re-position it. Can you give that a try?

**Comment by bearacuda** [comment]
Jeff,
     I did finally get it to work.  Not sure exactly what changed, but I
got results I could believe.  BTW, I used it try and determine a decrease
in blue light output from computer/cell phone displays using blue light
removing apps and screen covers.

Thank you,
Jason

**Comment by jywarren** [comment]
Oh, very good to hear, and cool! I'm closing for now; we'll catch new bugs in the upcoming Spectral Workbench 2.0 revamp; check it out: http://publiclab.org/notes/warren/02-10-2015/planning-for-spectral-workbench-2-0
