### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by YogiBGitHub** [publiclab/spectral-workbench#227]
Login no longer works correctly. The problem is both in Chome and Firefox. The initial login seems to be ok, but I am kept beeing asked to login when trying to got to capture spectra. Login again does not help, so I cannot see mye previous spectra or save any new ones.

**Comment by jywarren** [comment]
Hello, thanks for reporting. Can you tell us your username?

**Comment by YogiBGitHub** [comment]
Hi, my username is YogiB

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 9. november 2015 16:34
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub
Emne: Re: [spectral-workbench] Login problem (#227)

 

Hello, thanks for reporting. Can you tell us your username?

**Comment by YogiBGitHub** [comment]
It works now. I deleted cockies and all temp-data in my browser. Not sure why or what happened. But I am happy as long as it works.

**Comment by jywarren** [comment]
Oh, glad to hear it. Thanks.
