### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by bosonbeard** [publiclab/spectral-workbench#232]
I can not log into my profile and upload a photo of the spectrum.

I enter the password, I see window 1 (in the screenshot)
click YES, but after the transition to following page, I am not in the system. (screenshot 2)
I see again  "login" (not my nickname)

![login](https://cloud.githubusercontent.com/assets/5284540/11168243/6375c282-8b97-11e5-9549-014610eca309.jpg)

**Comment by bosonbeard** [comment]
Use UIE 11 and Chromium (iron) 43

**Comment by bosonbeard** [comment]
IE 11

**Comment by YogiBGitHub** [comment]
I am having the same problem - again. A couple of days ago I tried to delete cockies and tempfiles in the browser, and then it suddenly worked. But now the login does not work any more, no matter what I do, Chrome, Firefox, IE 11 or Edge.

**Comment by jywarren** [comment]
I'm sorry for the issues - we (@icarito and i) just forced SSL security for
publiclab.org and turned it on optionally for spectralwb.

I thought I'd made the necessary changes but i suspect somethings wrong
with them - I will be able to debug first thing tomorrow - apologies!

**Comment by jywarren** [comment]
Ah - on this line, don't know how I missed it: https://github.com/publiclab/spectral-workbench/blob/master/app/controllers/sessions_controller.rb

**Comment by jywarren** [comment]
Needs to be https

**Comment by jywarren** [comment]
OK - i've initiated a database migration to fix this. It should be resolved
in about 30 minutes -- can you test then and tell me if it worked?

THanks!

**Comment by jywarren** [comment]
Should be complete. If it works, can you please close this issue? Thanks!

**Comment by YogiBGitHub** [comment]
Many thanks Jeffrey! Now login works like a dream.

**Comment by YogiBGitHub** [comment]
Since I didn’t open this issue I cannot close it.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 15. november 2015 21:11
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub
Emne: Re: [spectral-workbench] can't login (#232)

 

Should be complete. If it works, can you please close this issue? Thanks!

**Comment by jywarren** [comment]
@bosonbeard can hopefully close it if the error is resolved for him too.

**Comment by bosonbeard** [comment]
yes, thanks
