### ISSUE TITLE
Cannot view uploaded spectrum

### ISSUE THREAD

**Issue by Starryblack** [publiclab/spectral-workbench#236]
Hi,

When i try to upload an image (100kb .jpeg) Spectral workbench always leads me to the Sorry something went wrong page. The spectrum appears in my dashboard but pressing it leads to that page. Is there possible a fix for this? Thanks.

username is wms 
![p1120813 2](https://cloud.githubusercontent.com/assets/16046770/11441441/01399cce-9547-11e5-8590-eba1167b8794.jpg)
using chrome
issue: https://spectralworkbench.org/spectrums/63638

**Comment by jywarren** [comment]
Hi, can you take a picture of the form you use to submit this image, so we
can see the title & metadata before you upload? This will help us debug.
Thanks for reporting!

**Comment by jywarren** [comment]
Please feel free to re-open, but as I haven't heard back, I'm going to close this up. Thanks!
