### ISSUE TITLE
compare SpectraPane doesn't display your own spectra by default or by selecting "Your Spectra"

### ISSUE THREAD

**Issue by YogiBGitHub** [publiclab/spectral-workbench#273]
When I am trying to compare with another spectrum, selecting "Your spectra", I get every others spectra, so It's really not usable. Must be some filtering error.

**Comment by steviepubliclab** [comment]
Also have this problem. I can't seem to find any of mine.

**Comment by jywarren** [comment]
We should fix this, but I think you can search for the ID # to find
spectra. See if that works?

**Comment by jywarren** [comment]
Maybe "your spectra" menu is not hooked up right.

**Comment by YogiBGitHub** [comment]
Can’t find the ID# either… but the name I have saved it with works.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 23. januar 2016 01:19
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub
Emne: Re: [spectral-workbench] Compare with another spectrum - not mine (#273)

 

We should fix this, but I think you can search for the ID # to find
spectra. See if that works?

**Comment by steviepubliclab** [comment]
I can search for a spectra I named and find it that way. I can't seem to
find on my spectra scan where the individual number is.

**Comment by jywarren** [comment]
You can use the # from the URL. But I'm adding this to outstanding bugs to fix for 2.0, thanks.

**Comment by jywarren** [comment]
I believe this is resolved now -- can you give it a try?
