### ISSUE TITLE
Delete spectra and equalize height

### ISSUE THREAD

**Issue by YogiBGitHub** [publiclab/spectral-workbench#274]
In the new version I miss simple things like deleting a spectra and equalizing height (when comparing).

**Comment by jywarren** [comment]
Hello, thanks for reporting; on which page?

**Comment by YogiBGitHub** [comment]
Here is the url for the spectrum I try to delete:

https://spectralworkbench.org/spectrums/show2/68729

Maybe I start to get blind, but I cannot find a way to delete a spectrum.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 22. januar 2016 22:53
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub
Emne: Re: [spectral-workbench] Delete spectra and equalize height (#274)

 

Hello, thanks for reporting; on which page?

**Comment by jywarren** [comment]
It should be on the left next to the "Like" button. But if you can't see it, please upload a screenshot and re-open this issue. Thanks!

**Comment by YogiBGitHub** [comment]
Yes, I can see there is a delete icon, but for some spectra it is disabled.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 25. januar 2016 16:18
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub
Emne: Re: [spectral-workbench] Delete spectra and equalize height (#274)

 

It should be on the left next to the "Like" button. But if you can't see it, please upload a screenshot and re-open this issue. Thanks!

**Comment by jywarren** [comment]
If you hover over it, does it tell you why?

**Comment by YogiBGitHub** [comment]
No, when disabled, it does not tell anything.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 25. januar 2016 17:23
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub
Emne: Re: [spectral-workbench] Delete spectra and equalize height (#274)

 

If you hover over it, does it tell you why?

**Comment by jywarren** [comment]
OK, we'll try to address this in the next release -- thanks! Some are
disabled because they are being used by other spectrums' operations.

**Comment by YogiBGitHub** [comment]
Thanks. I guessed there were some dependencies behind.

I also miss the “equalize height” feature. I use this to make a relative output comparison. In each measurement of some red leds I use stronger blue leds as a reference. So when comparing several spectra, I use equalize height to level all the blue reading. Then the red ones can be compared relatively speaking. Please see the attached picture, where the blue peaks are cut away. It has been very useful.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 25. januar 2016 20:49
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub
Emne: Re: [spectral-workbench] Delete spectra and equalize height (#274)

 

OK, we'll try to address this in the next release -- thanks! Some are
disabled because they are being used by other spectrums' operations.
