### ISSUE TITLE
Saving spectra does not work anymore

### ISSUE THREAD

**Issue by YogiBGitHub** [publiclab/spectral-workbench#311]
When saving a new spectra with an existing calibration, it is not saved. The same page is reloaded without any other action.

**Comment by jywarren** [comment]
I believe this is now resolved, thanks! A couple other users had posted about the bug.

**Comment by YogiBGitHub** [comment]
Tried again, but it didn’t work.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 5. februar 2016 16:13
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub
Emne: Re: [spectral-workbench] Saving spectra does not work anymore (#311)

 

I believe this is now resolved, thanks! A couple other users had posted about the bug.

**Comment by jywarren** [comment]
Ack, sorry, rebooting the app took a little longer than I'd expected. I
just tested it and it's working again now.

**Comment by YogiBGitHub** [comment]
Very good. Now everything is ok. Thanks.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 5. februar 2016 16:18
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub
Emne: Re: [spectral-workbench] Saving spectra does not work anymore (#311)

 

Ack, sorry, rebooting the app took a little longer than I'd expected. I
just tested it and it's working again now.

**Comment by jywarren** [comment]
super!
