### ISSUE TITLE
timestamps displayed in UTC instead of user timezone

### ISSUE THREAD

**Issue by ethanbass** [publiclab/spectral-workbench#324]
I took this spectra on Feb 11 at 5 pm but the time stamp says 23:01. The time stamps on all of my spectra taken in spectral workbench 2.0 seem to be offset by 6 hours. 

![screen shot 2016-02-11 at 5 05 40 pm](https://cloud.githubusercontent.com/assets/15876283/13012530/49c80be0-d171-11e5-8a53-d94ccf6f58e1.jpg)

**Comment by jywarren** [comment]
Thanks; this page has some resources on determing user timezone:
http://stackoverflow.com/questions/4269270/rails-3-setting-the-timezone-to-the-current-users-timezone

**Comment by jywarren** [comment]
We can use http://momentjs.com/timezone/ -- we're already using moment.js, actually!

**Comment by jywarren** [comment]
Hmm. I'm a bit loathe to introduce a whole new library for this, or to execute further javascript just to parse a date into a local timezone. It kind of sucks, but I'm just going to add "UTC" to the end of that timestamp. If you feel strongly about it, please speak up and we can do something more.
