### ISSUE TITLE
mouse hover-over tooltip with point data is no longer appearing

### ISSUE THREAD

**Issue by YogiBGitHub** [publiclab/spectral-workbench#361]
When pointing to the graph on a saved spectrum, the measurement is no longer visible. Tried two different browsers, Chrome and Edge. Not tried a different computer though.

Username: YogiB

**Comment by jywarren** [comment]
Hi, do you mean the little tooltip/popup that follows your mouse? Confirmed
this at https://spectralworkbench.org/spectrums/55073, thank you for
reporting.

**Comment by jywarren** [comment]
Confirmed that this is not working on SpectralWorkbench.js either: https://publiclab.github.io/spectral-workbench.js/examples/

Probably related to stylesheet classname changes. Also the image itself is not properly masked.

**Comment by YogiBGitHub** [comment]
Yes, that’s correct. It is very difficult to measure the exact peak wavelengths without this little helper.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 25. april 2016 21:47
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub; Author
Emne: Re: [publiclab/spectral-workbench] The overlay measurement is gone (#361)

 

Hi, do you mean the little tooltip/popup that follows your mouse? Confirmed
this at  <https://spectralworkbench.org/spectrums/55073> https://spectralworkbench.org/spectrums/55073, thank you for
reporting.

**Comment by jywarren** [comment]
Sorry for the bug! I have it on my schedule to look at tomorrow morning.
Thank you for your patience.

**Comment by jywarren** [comment]
I think this is fixed, I'll publish the change in the next 10 minutes. Can you confirm then?

**Comment by jywarren** [comment]
Sorry, please hold, still figuring this out.

**Comment by jywarren** [comment]
OK, this is published now. I've confirmed that it works in a recent Chrome; does it work for you?

**Comment by YogiBGitHub** [comment]
Thanks Jeffrey. Now everything seems fine, also in Chrome.

 

Fra: Jeffrey Warren [mailto:notifications@github.com] 
Sendt: 26. april 2016 22:22
Til: publiclab/spectral-workbench
Kopi: YogiBGitHub; Author
Emne: Re: [publiclab/spectral-workbench] mouse hover-over tooltip with point data is no longer appearing (#361)

 

OK, this is published now. I've confirmed that it works in a recent Chrome; does it work for you? 

—
You are receiving this because you authored the thread.
Reply to this email directly or  <https://github.com/publiclab/spectral-workbench/issues/361#issuecomment-214874186> view it on GitHub  <https://github.com/notifications/beacon/ANHaeUYG-Y8zBXjjW_Vk364EQg8NfrPuks5p7nPlgaJpZM4IPLVK.gif> 

  _____  

No virus found in this message.
Checked by AVG - www.avg.com
Version: 2016.0.7539 / Virus Database: 4563/12108 - Release Date: 04/26/16

**Comment by jywarren** [comment]
Super! Thanks.
