### ISSUE TITLE
repeat error saving calibration

### ISSUE THREAD

**Issue by wlallen** [publiclab/spectral-workbench#387]
## What happened just before the problem occurred

Whether I attempt to copy an existing calibration, or just 'calibrate' and add the reference pixel numbers from my calibration image manually, when I try to save the calibration I get an error "there was an error" and "The tag you've applied couldn't be saved, but it's been run locally.", and the save button just spins. Sometimes if I return to my dashboard and then reenter the file the calibration appears, but not always. I've followed all the tutorials closely and can't find any mistake. Any assistance much appreciated.

## Relevant URLs

https://spectralworkbench.org/spectrums/98656

## PublicLab.org username

shonkhor

## Browser, version, and operating system

Google Chrome  v.55.0.2883.87, Windows 7

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
I believe this may be related to #394 with a pending fix in #395! Merging to track together.
