### ISSUE TITLE
The wavelength is null in csv, json, xml

### ISSUE THREAD

**Issue by bosonbeard** [publiclab/spectral-workbench#391]
## What happened just before the problem occurred
Smartphone spectrometer, manual uploading, manual calibration
After calibration in the files for downloading (csv, json, xml) , the wavelength is zero(Null). On the chart, everything is correct. Similar already had a couple of years ago in the old interface.

## Relevant URLs

https://spectralworkbench.org/spectrums/111365

## PublicLab.org username
bosonbeard
(to help reproduce the issue)

## Browser, version, and operating system
MS Edge, SrWare Iron (chromium) 58.0.3050.0 , OS Win 10

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by bosonbeard** [comment]
I realized that this depends on the length of the image, cropped the image in another version and the error was gone
https://spectralworkbench.org/spectrums/111367

**Comment by jywarren** [comment]
Ah, was it that the original image was too large? I think the JSON encoding of the data could exceed the available space in the data storage column we use... but if so we should return a related error.

**Comment by bosonbeard** [comment]
I do not know what is the cause of the error, but this problem occurs quite often. Here is another example
https://spectralworkbench.org/spectrums/98536

**Comment by jywarren** [comment]
I believe this may be related to #394 with a pending fix in #395! Merging to track together.
