### ISSUE TITLE
Cannot Copy Calibration

### ISSUE THREAD

**Issue by katfish904** [publiclab/spectral-workbench#392]
## What happened just before the problem occurred
I uploaded my CLF spectrum and calibrated. Uploaded my other spectrums and clicked "copy calibration" However, calibration does not complete, with an error
"The tag you've applied couldn't be saved, but it's been run locally."

## Relevant URLs

https://

## PublicLab.org username
katfish904

(to help reproduce the issue)

## Browser, version, and operating system
windows 7
chrome v.61.0.3163.100

For bug reports, fill out the above template; for feature requests, you can delete the template.

**Comment by jywarren** [comment]
I believe this may be related to #394 with a pending fix in #395! Merging to track together; thanks for reporting!
