### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by Artik-Man** [publiclab/spectral-workbench#398]
## What happened just before the problem occurred
I can not log in

## Relevant URLs
https://spectralworkbench.org/login

## PublicLab.org username
artik.alpha@ya.ru

## Browser, version, and operating system
Chrome 65, Windows 10

**Comment by SidharthBansal** [comment]
Hi, try logging through public lab or any provider. If still you face problem, please tell which icon did you clicked. We will be happy to help

**Comment by SidharthBansal** [comment]
I hope it works now. Please feel free to open up an issue again if problem persists
