### ISSUE TITLE
improve CSV format consistency and standards-compliance

### ISSUE THREAD

**Issue by btbonval** [publiclab/spectral-workbench#4]
The CSV download of a spectrum is two (unlabeled) columns. I presume this is only the spectral data.

For JSON, XML, and HTML, the full set of metadata and data is included.

One issue that needs to be addressed is that the spectral data is always returned as embedded JSON (e.g. in XML it is `<data>{ json stuff }</data>`).

The current format returned by the CSV is a good start towards demuxing the JSON into CSV, but we need to append/prepend the rest of the metadata as well as provide column names.

****

Addendum by @jywarren: include FWHM values in CSV; details in https://github.com/jywarren/spectral-workbench/issues/137

**Comment by jywarren** [comment]
The "raw" alternate form of CSV was requested early on; it includes:

    Wavelength,Average,Red,Green,Blue
    -194.99,0,1,0,0
    -192.00,0,0,0,0

Also merging in @tclarke's request in jywarren/spectral-workbench#136 for floats:

> Many spectral tools (ENVI, Opticks, etc.) expect reflectance/transmission/emissivity data to be floats the range 0.0-1.0 (or >1.0 for emission spectra) instead of integers. Normalizing to this range should increase the usability of exported spectra.

@tclarke - would additional metadata above or below in a CSV file cause trouble vs. ones produced in ENVI or Opticks?

**Comment by jywarren** [comment]
Possible redundancy with #24

**Comment by jrslagle** [comment]
I was wondering if the "CSV (raw)" button can be removed and the CSV button serves up a csv with a header line and the five columns. 

In the code is this legacy which is the template that generates the csv with no header and only two columns.
render :template => "spectrums/show.csv.erb" # formatted for SpectraOnline.com

Do you still want to support SpectraOnline.com?

**Comment by jywarren** [comment]
Hi - the "raw" CSV was a special request from someone. But it was honestly so long ago, I can't even find the email! So, perhaps it's reasonable to remove the "raw" version. Thanks!

**Comment by btbonval** [comment]
I think it's fair to say that in any environment where CSV is being processed, one row of headers can be removed in a trivial fashion regardless of that environment.

**Comment by jrslagle** [comment]
I believe this is resolved now, right?

**Comment by jywarren** [comment]
Yep! Although i just found a typo reported by Ankur and am pushing a fix in
a moment. Thanks, James!

Are you interested in continuing to contribute? We badly need the help,
even if it's just a small contribution. I'd be happy to help you find
something to work on that fits your interests.

**Comment by jrslagle** [comment]
I am interested in continuing to contribute, as time permits. I'm very new to rails, so anything I push and pull request to my own master, I have my expert code review first. I've been looking at the open issues and taking on the oldest one that I think I can handle. I have my eye on issue #24 next.

**Comment by jywarren** [comment]
Super! Yes, i also was thinking about how we might more efficiently return
set JSON which includes all spectra for the set. Right now we assemble it
manually on the server side and it takes a while for big sets.
