### ISSUE TITLE
Service becomes unresponsive

### ISSUE THREAD

**Issue by icarito** [publiclab/spectral-workbench#436]
It was reported that SW failed to respond this morning. There was a **critical** alert for Load average at 4:36AM , but no alert for HTTP. It could be the Rackspace backup system which we know uses a lot of RAM. If it is the case we should prioritize switch backup systems.

**Comment by icarito** [comment]
Here's the graph and endpoint list for this morning's slowdown:
![image](https://user-images.githubusercontent.com/199755/52416547-d5735d00-2ab7-11e9-9398-8fcaf8f7ebbd.png)

Here's a link to the graph https://oss.skylight.io/app/applications/Wnv2jzIUWl5x/1549529820/18m/endpoints

**Comment by jywarren** [comment]
In general if we may need to be moving off of Rackspace, we should maybe
prioritize a separate backup system anyways. Thanks, Sebastian!

**Comment by icarito** [comment]
Thank you! Just now got another critical alert for high load on spectralworkbench, found the DB a bit busy:
![image](https://user-images.githubusercontent.com/199755/52453063-aab6f200-2b13-11e9-9666-21fc27675e7f.png)

**Comment by icarito** [comment]
![image](https://user-images.githubusercontent.com/199755/52453213-49435300-2b14-11e9-9f4f-5c7b2e2cf1be.png)
I'll check if skylight agrees! Perhaps there is a query we can optimize.

**Comment by icarito** [comment]
Could it be setscontroller? 
![image](https://user-images.githubusercontent.com/199755/52453381-0fbf1780-2b15-11e9-8106-603c85e7df8b.png)

https://www.skylight.io/app/applications/Wnv2jzIUWl5x/recent/6h/endpoints/SetsController%23show?responseType=json

**Comment by jywarren** [comment]
I believe we've addressed this in #457!
