### ISSUE TITLE
Merging before Travis CI 

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/spectral-workbench#442]
I am trying to install Spectral Work Bench. I fixed a typo in the installation manuals. I was able to merge before the travis successfully passed, unlike the plots2 repo.
I think this should be fixed
![image](https://user-images.githubusercontent.com/20972099/54089918-51e9ac00-4394-11e9-9bae-bc20470ba3f7.png)

**Comment by SidharthBansal** [comment]
See it is under closed issues @jywarren and it is running.

**Comment by jywarren** [comment]
Thanks @SidharthBansal !!!

**Comment by SidharthBansal** [comment]
Is it fixed? You have closed this issue.

**Comment by jywarren** [comment]
yep!
