### ISSUE TITLE
Sidebar inconsistent with the header

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/spectral-workbench#443]
![image](https://user-images.githubusercontent.com/20972099/54090044-f28c9b80-4395-11e9-9dce-e7f876428a21.png)
I found after login we have username listed on the header but in the sidebar there is option for the sign up.

**Comment by jywarren** [comment]
Ah, good catch. I think this could be a renaming of the button because it's
prompting people to subscribe to questions from PL.org, not to sign up for
SWB. Good eye!

**Comment by geekychaser** [comment]
Can i give it a try?

**Comment by SidharthBansal** [comment]
Yep

**Comment by gr455** [comment]
Hey, Can I work on this issue?
