### ISSUE TITLE
Make login modal more modern

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/spectral-workbench#473]
Currently, the login modal and it's icons are not very modern:
![spectral-old-login](https://user-images.githubusercontent.com/52892257/71926349-686aba80-3193-11ea-8d62-37954044945f.png)

I think we could improve this to make it more like Mapknitter's:
![mapknitter-login](https://user-images.githubusercontent.com/52892257/71926389-7f111180-3193-11ea-8a2f-1f47fc6b00b3.png)

I will work on this. What do you think @publiclab/designers?

**Comment by jywarren** [comment]
That'd be great! One issue though is that SWB is on Bootstrap 3, isn't it?
Not 4?

**Comment by Uzay-G** [comment]
That should be fine, I can use custom styling if necessary.
