### ISSUE TITLE
Test databse inconsistent

### ISSUE THREAD

**Issue by gr455** [publiclab/spectral-workbench#488]
Problem:
1) The test database has `user_id = 0` for the comments model whereas there is no User with `id = 0`. This inconsistency can create problems while writing tests
2) The test database has one `User.first` 's `tag.spectrum_id = 1` , but none of the spectra have `id = 1` 

Solution:
change the required fields in the test database seed.

@publiclab/community-reps , I would like to know your views on this

**Comment by cesswairimu** [comment]
Hey @gr55, is this from seed file?

**Comment by gr455** [comment]
> Hey @gr55, is this from seed file?

Yeah about that, can you tell me how the test database is seeded?

**Comment by alaxalves** [comment]
Fixed by #493
