### ISSUE TITLE
Weekly community Check-In #54 - How are you doing? Check-in with the us

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/spectral-workbench#497]
We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart:. You are also welcome to share fun-fact :smile:, new ideas :bulb:, your learning goals :ballot_box_with_check:.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

#### Next Check-in
If you would like to open the next weekly check-in please comment below.

Thanks everyone for making PL awesome and have a great week ahead :balloon:

**Comment by SidharthBansal** [comment]
Duplicate

**Comment by cesswairimu** [comment]
I didn't realize I created two issues...thanks @SidharthBansal for this catch :+1:
