### ISSUE TITLE
Some paths returning 404

### ISSUE THREAD

**Issue by icarito** [publiclab/spectral-workbench#644]
These URLs are expected to exist:

https://spectralworkbench.org/upload

https://spectralworkbench.org/spectrums/latest/220369.csv

**Comment by icarito** [comment]
I can actually reach https://spectralworkbench.org/upload

**Comment by norenTM** [comment]
When logged in, I'm not able to reach https://spectralworkbench.org/upload - have also tested this on different browsers.

**Comment by jywarren** [comment]
Linking to #641

**Comment by jywarren** [comment]
https://stable.spectralworkbench.org/spectrums/latest/220369.csv

**Comment by jywarren** [comment]
We need to check if other pages are erroring, besides these. Wasn't there still an error saving?

**Comment by jywarren** [comment]
https://stable.spectralworkbench.org/spectrums/latest/220369.csv is a routing error:

```
Started GET "/spectrums/latest/220369.csv" for 72.92.236.166 at 2021-06-15 22:13:15 +0000
ActionController::RoutingError (No route matches [GET] "/spectrums/latest/220369.csv"):
```

**Comment by jywarren** [comment]
We'll add a route for CSVs (probably `params[:format]` thing) and check in GitPod.

**Comment by jywarren** [comment]
we should watch for similar ones in case other routes or queries need fixing!!
