### ISSUE TITLE
recent calibrations not available to capture interface

### ISSUE THREAD

**Issue by jywarren** [publiclab/spectral-workbench#7]
1) We should have a button that lets you choose a recent calibration, in the /capture interface. It should show an up-to-date list of recent calibrations, ajaxly in case the capture page hasn't been reloaded

2) We should have the button turn red when a new calibration is detected, via 10-sec AJAX polling, and display an alert that a new calibration is available with a button to use it.

**Comment by vpowerrc** [comment]
Shall we close this issue?

**Comment by jywarren** [comment]
Yep!
