### ISSUE TITLE
fixing bundler version mismatch with containers

### ISSUE THREAD

**Issue by jywarren** [publiclab/spectral-workbench#720]
https://github.com/publiclab/spectral-workbench/pull/717

https://github.com/publiclab/plots2/issues/9871

```
gitpod /workspace/spectral-workbench $ bundle --version
Bundler version 1.17.3
```

**Comment by icarito** [comment]
Yes, the issue is that when building the container, version 1.17.3 is installed, and so it fails to install Gems. Is it necessary to declare bundler version? I think it should work if we just remove those lines (but probably not best practice).

**Comment by jywarren** [comment]
I think they're auto-generated by Bundler so that they'll keep getting re-added. And i wonder if there are some breaking changes in bundler syntax? Even if we're not encountering them they did change a major version number.

**Comment by jywarren** [comment]
Resolving in https://github.com/publiclab/spectral-workbench/pull/721 - thanks!
