### ISSUE TITLE
Add welcome bot config file to .github 

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/spectral-workbench#758]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Add** the file [config.yml]($BRANCH_URL) in the `spectral-workbench` repository in the `.github` folder (press the little pen Icon) with the content as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

.github/config.yml
```diff
# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue! This space is [protected by our Code of Conduct](https://publiclab.org/conduct) - and we're here to help.
  Please follow the issue template to help us help you 👍🎉😄
  If you have screenshots [or a gif](https://publiclab.org/gifs/) to share demonstrating the issue, that's really helpful! 📸
  Do join our [Gitter channel](https://gitter.im/publiclab/publiclab) for some brainstorming discussions. 
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request!  This space is [protected by our Code of Conduct](https://publiclab.org/conduct) - and we're here to help.
 `Dangerbot` will test out your code and reply in a bit with some pointers and requests.
 Also please refer [here](https://github.com/publiclab/plots2/issues/3840) for installation help 💿
 There may be some errors, **but don't worry!** We'll work through them with you! 👍🎉😄
 <br />
 One thing that can help to get started is to make sure you've included a link back to the original issue you're solving, in the 
 format `fixes #0000` (for example). And to make sure the PR title describes what you're trying to do! (often it can be the same as 
 the issue title) Thanks! 🙌 
 <br />
 Then, you can [say hello in our chatroom](https://gitter.im/publiclab/publiclab) & share a link to this PR to get a review! 👋 ✅ 
 
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! 🙌🎉⚡️
 Your code will likely be published to PublicLab.org in the next few days, but first it will be published to https://stable.publiclab.org/ (it will take some minutes for this to load, and until then you may see logs from the build process). Please test out your work on this testing server and report back with a comment that all has gone well!
 Do join our weekly check-in to share your this week goal and the awesome work you did 😃. Please find the link to our latest check-in [here](https://github.com/publiclab/plots2/issues/5627) 📝
 Now that you've completed this, you can help someone else take their first step!
 Reach out to someone else working on theirs on [Public Lab's code welcome page](https://code.publiclab.org#r=all) (where you'll now be featured as a recent contributor!). Thanks!
 <details>
 <summary><b>Help others take their first step</b></summary>
 <p>Now that you've merged your first pull request, you're the perfect person to help someone else out with this challenging first step. 🙌 </p>
 <p><a href="https://code.publiclab.org#r=all">https://code.publiclab.org</a></p>
 <p>Try looking at this list of `first-timers-only` issues, and see if someone else is waiting for feedback, or even stuck! 😕 </p>
 <p>People often get stuck at the same steps, so you might be able to help someone get unstuck, or help lead them to some documentation that'd help. Reach out and be encouraging and friendly! 😄 🎉 </p>
 <p>Read about <a href="https://github.com/publiclab/plots2/issues/3458">how to help support another newcomer here</a>, or find <a href="https://github.com/publiclab/plots2/labels/support">other ways to offer mutual support here</a>.</p>
 </details>
<p>Join our Gitter channel <a href="https://gitter.im/publiclab/publiclab">here</a> to connect with other contributors</p> :inbox_tray:


# It is recommended to include as many gifs and emojis as possible
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by abhi30996** [comment]
Hi. I would like to work on this. Is this issue still available?

**Comment by prius2055** [comment]
Hi, I am an Outreachy applicant and would like to work on this issue. Can it be assigned to me please?

**Comment by TildaDares** [comment]
Hi @abhi30996, yes you can work on it!
