### ISSUE TITLE
Find broken routes on the spectral workbench app and add them to a list here

### ISSUE THREAD

**Issue by Georjane** [publiclab/spectral-workbench#833]
Hi @Tlazypanda @jywarren @TildaDares 👋🏽 
Please I was wondering if there are any broken routes we might have come across on the SW or have been reported by users so I could reconnect them?
So far, after going through most of the links in the SW, most of the routes seem to be working great. I noticed just one broken link on the contributor's name in the spectra section whose issue I addressed [here](https://github.com/publiclab/spectral-workbench/issues/809)

Please are there other broken routes that I missed?
Thank you. 🙏🏽 🙏🏽🙏🏽

**Comment by Georjane** [comment]
List of broken routes
- All author links **(pzgeorjane)** in the images below are broken
![image](https://user-images.githubusercontent.com/60772732/148932732-233a6272-0606-4815-9098-027909d5da7a.png)
![image](https://user-images.githubusercontent.com/60772732/148932882-189fc651-88e4-42c7-9196-d5c407f10eed.png)
![image](https://user-images.githubusercontent.com/60772732/148932940-9c013a8a-8f88-47b4-b71f-842c281a7def.png)

**Comment by Georjane** [comment]
@TildaDares @jywarren @Tlazypanda 
I keep seeing the letter h like ` <%=h ` in front of opening tags like in the image below. I wish to find out if this is a bug or there is a meaning to it. I have seen this in a couple of places. Thank you. 🙏🏽 

_**app/views/macros/show.html.erb**_
![image](https://user-images.githubusercontent.com/60772732/148935850-eabd07df-b796-4f70-bfc3-94f83577b4fb.png)

**Comment by TildaDares** [comment]
@Georjane `<%= h` is an alias for `html_escape`. It is used to escape HTML tags https://api.rubyonrails.org/classes/ERB/Util.html#method-c-h

**Comment by Georjane** [comment]
> @Georjane `<%= h` is an alias for `html_escape`. It is used to escape HTML tags https://api.rubyonrails.org/classes/ERB/Util.html#method-c-h

oh, I see. it makes a lot of sense now. thank you @TildaDares

**Comment by Georjane** [comment]
@Tlazypanda 
please what do we mean by looking at the blame view here,
you can see recently fixed ones in the "blame" view of https://github.com/publiclab/spectral-workbench/blame/main/config/routes.rb
