### ISSUE TITLE
Protect routes with functional tests

### ISSUE THREAD

**Issue by Georjane** [publiclab/spectral-workbench#834]
Hi @jywarren @Tlazypanda @TildaDares 👋🏽 
For the functional tests, I noticed that we have about 13 controllers in the SW but we have functional tests for just about 9 controllers. So the following controllers are not being tested, device_controller, macros_controller, match_controller, and application_controller.

Just to be sure that I would be writing tests for these controllers?
Also, I was wondering what Macros in the macros_controller are?

Thank you! 🙏🏽

**Comment by Georjane** [comment]
I tried running the following test on the macros_controller but I did not exactly understand the response I was getting
```
# frozen_string_literal: true

require 'test_helper'

class MacrosControllerTest < ActionController::TestCase
  test 'should get macros index' do
    get :index
    assert_response :success
    # assert_not_nil assigns(:spectrums)
  end
end
```

**Comment by TildaDares** [comment]
Hi Jane, what kind of responses did you get? 

I don't know if this helps you understand what macros do
https://github.com/publiclab/spectral-workbench/blob/abe48d023d8c113e9b8c30718932a630b99ec3fc/app/views/macros/_pane.html.erb#L5

**Comment by TildaDares** [comment]
I also found this article on https://publiclab.org/wiki/spectral-workbench-api-v1#Macros on Public Lab. It's deprecated but it should give you a better sense oof what Macros are.

**Comment by Georjane** [comment]
> Hi Jane, what kind of responses did you get?
> 
> I don't know if this helps you understand what macros do
> 
> https://github.com/publiclab/spectral-workbench/blob/abe48d023d8c113e9b8c30718932a630b99ec3fc/app/views/macros/_pane.html.erb#L5

I tried accessing the enpoint /macros locally but I was getting the following error
![image](https://user-images.githubusercontent.com/60772732/148920280-7c21e908-d22f-4a45-bdb6-f984240578f2.png)

When I try accessing it on the live version I have this page
![image](https://user-images.githubusercontent.com/60772732/148920479-a658aed5-144c-4ff6-806c-a88ff451f54a.png)

**Comment by Georjane** [comment]
> I also found this article on https://publiclab.org/wiki/spectral-workbench-api-v1#Macros on Public Lab. It's deprecated but it should give you a better sense oof what Macros are.

ohhh I understand macros now. Thank you very much @TildaDares 
I think I understand the error now

**Comment by Georjane** [comment]
Now able to create a macro but got the following error from the show method
![image](https://user-images.githubusercontent.com/60772732/148931832-c926ead7-1405-4e2b-9b58-62e4e8fba789.png)

**Comment by TildaDares** [comment]
@Georjane I think `find_by_title` method is supposed to be passed one argument. You can try this format and see if it works
https://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by

**Comment by Georjane** [comment]
> @Georjane I think `find_by_title` method is supposed to be passed one argument. You can try this format and see if it works https://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by

thanks for the link @TildaDares 
let me read more on this

**Comment by Georjane** [comment]
@TildaDares thank you, @Tlazypanda helped me out with the following syntax that works
`@macro = Macro.find_by :title params[:id], conditions: { user_id: @user.id }, order: 'id DESC'`
