### ISSUE TITLE
comment posting says "There was an error" in popup, but still posts

### ISSUE THREAD

**Issue by jywarren** [publiclab/spectral-workbench#88]
http://spectralworkbench.org/analyze/spectrum/44204

![comment-error](https://cloud.githubusercontent.com/assets/24359/6379735/69854e90-bd02-11e4-8239-ef8d1b6673f2.png)

**Comment by jywarren** [comment]
This may be due to comment notifications; we should check that and write tests!

**Comment by jywarren** [comment]
This doesn't happen on master on my local env but I also fixed the comment notifications in the refactoring I did, so that might've solved it.

**Comment by btbonval** [comment]
`git checkout {part of a commit hash}` can check out the repo at any previous point in commit-time. You can always back track your code base to before you merged the changes into master.

**Comment by btbonval** [comment]
... rather than using prod as the litmus test, that is ;)

**Comment by jywarren** [comment]
Well, we had a scheduled push to production today anyways, and it wasn't going to get worse than it already was :-P

The push did not fix it. I'll dig a bit more.

**Comment by jywarren** [comment]
Mailers hadn't been updated to Rails 3.2 conventions. Done now, working.
