### ISSUE TITLE
comments show html tags

### ISSUE THREAD

**Issue by jywarren** [publiclab/spectral-workbench#89]
![comment-error](https://cloud.githubusercontent.com/assets/24359/6379745/7e74c8d0-bd02-11e4-9b79-22e821883ba2.png)

(http://spectralworkbench.org/analyze/spectrum/44204) -- ignore the error in above image; just trying to show the `<p>` tags

**Comment by btbonval** [comment]
FTFY
![7e74c8d0-bd02-11e4-9b79-22e821883ba2](https://cloud.githubusercontent.com/assets/880439/6379810/f32aba22-bd02-11e4-8196-53d83f9dcadf.png)

**Comment by jywarren** [comment]
this should just be a matter of adding `raw` i.e. `<%= raw comment.body %>` because of new Rails 3 rules

**Comment by jywarren** [comment]
Very odd -- this doesn't seem to happen in my local env. this line shows it may require the addition of `raw` in the template: https://github.com/publiclab/spectral-workbench/blob/master/app/views/comments/index.html.erb#L19
