### ISSUE TITLE
can't select existing calibration (chrome & firefox, mac & windows)

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/spectral-workbench#98]
I can't assign an existing calibration to spectra in firefox or chrome on mac or windows. I can't seem to assign a calibration at time of capture or in the analyze window.

never seen this problem before...
![screen shot 2015-03-02 at 7 30 37 pm](https://cloud.githubusercontent.com/assets/1203280/6456224/19e1adaa-c114-11e4-8ced-8cb5fdcfd305.png)
![screen shot 2015-03-02 at 7 39 35 pm](https://cloud.githubusercontent.com/assets/1203280/6456223/19e04870-c114-11e4-8dce-2bff3cbae405.png)

**Comment by jywarren** [comment]
Ah, this is probably a bug introduced in the new software. Will take a look
tomorrow afternoon :-(

On Mon, Mar 2, 2015 at 10:41 PM, mathew lippincott <notifications@github.com

**Comment by jywarren** [comment]
OK, this is very odd -- i do see the buttons myself when logged in, but am wondering if somehow the table shown is pushed to the right off the edge of the window. Can you try selecting the text and dragging right, to see if there's content cut off? 

If that is correct, I can fix the column width.

**Comment by mathewlippincott** [comment]
hmm.. that doesn't seem to do it.  I know I've lost buttons from small windows, but even on a big monitor I'm seeing the issue.

**Comment by jywarren** [comment]
Plopped into a gist here: https://gist.github.com/gists

On Thu, Mar 5, 2015 at 12:12 PM, mathew lippincott <notifications@github.com

**Comment by jywarren** [comment]
OK -- I think i identified the problem and fixed it in bc79269ca60e99a3313f05d7128b5100b749598b, 439b718254cf57e9066e826e80c30cab97bfe128, and 0899dbe35e61559a537f24f91c535cc12e6276f6

Can you test and reopen if it doesn't work?

**Comment by mathewlippincott** [comment]
nope, still doesn't work.

**Comment by mathewlippincott** [comment]
seems to work for Stevie, but I can't find a calibration button anywhere.

**Comment by jywarren** [comment]
When I check, I don't see that the spectra in your screenshot are themselves calibrated -- are you sure they are, or that you've also searched for calibrated spectra? I think I can also make it only display calibrated spectra, which will make finding the most recent one easier.

**Comment by jywarren** [comment]
I've made it so it only shows calibrated spectra. I don't know if that was the problem, but want to confirm that before continuing to investigate. Can you try?

**Comment by mathewlippincott** [comment]
well, I can't calibrate my spectra so they aren't calibrated.... but whatever you did seemed to fix the issue.

**Comment by jywarren** [comment]
I think the uncalibrated spectra were occupying the whole visible list, so removing them let you see and choose the most recent calibrated ones. 

Do you think this is solved completely now, or would you like to see pagination on the search results, so you can dig up very old calibrations? I'm going to close, but if you would like the latter, pls re-open.

**Comment by jywarren** [comment]
And thanks for reporting!
